name = "daxecraft"
author = "encode42"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2dded3e50202b98756b59adf28a27c05d8413379c79180b3bbf46c63005f6b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
